[project]
name="chameleon"
version="0"
cppversion="c++11"
debug=true
cflag=""#额外参数 默认为空
compiler="g++"
ccache=true # 启用ccache 高速编译
apps=[
    "apps",
    "cmds",
    "conf",
    "contrib",
    "core",
    "db",
    "http",
    "middleware",
    "template",
    "urls",
    "utils",
    "views"
]
depends=[
    #"test$0"
]
